output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.cluster-1.cluster_endpoint
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.cluster-1.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.cluster-1.config_map_aws_auth
}

output "region" {
  description = "AWS region."
  value       = var.aws_region
}
